# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 759a4d0d4a4eb68dbdad1e64cc818eed7f58670884a9ec83d767dc24904f89368ca872e10b03c4fe62f4a5008a7f14be8c957006f3f157bec20685d7ce68f156

test:
  secret_key_base: e4a0bafe9f424f9614f0554f4bf2605b402d0a31846970e23a507ffe7c64797680d732418502258306ff69c588d543c8aa2b3bfec2b8cb0d32ad8aecd8a54292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
